sudo: false
language: c
cache:
  directories:
  - "$HOME/.ghc"
  - "$HOME/.cabal"
  - "$HOME/.stack"
matrix:
  include:
  - env: BUILD=cabal GHCVER=7.8.4 CABALVER=1.18 HAPPYVER=1.19.5 ALEXVER=3.1.7
    compiler: ": #GHC 7.8.4"
    addons:
      apt:
        packages:
        - cabal-install-1.18
        - ghc-7.8.4
        - happy-1.19.5
        - alex-3.1.7
        sources:
        - hvr-ghc
  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.22 HAPPYVER=1.19.5 ALEXVER=3.1.7
    compiler: ": #GHC 7.10.3"
    addons:
      apt:
        packages:
        - cabal-install-1.22
        - ghc-7.10.3
        - happy-1.19.5
        - alex-3.1.7
        sources:
        - hvr-ghc
  - env: BUILD=cabal GHCVER=8.0.2 CABALVER=1.24 HAPPYVER=1.19.5 ALEXVER=3.1.7
    compiler: ": #GHC 8.0.2"
    addons:
      apt:
        packages:
        - cabal-install-1.24
        - ghc-8.0.2
        - happy-1.19.5
        - alex-3.1.7
        sources:
        - hvr-ghc
  - env: BUILD=cabal GHCVER=head  CABALVER=head HAPPYVER=1.19.5 ALEXVER=3.1.7
    compiler: ": #GHC HEAD"
    addons:
      apt:
        packages:
        - cabal-install-head
        - ghc-head
        - happy-1.19.5
        - alex-3.1.7
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS=""
    compiler: ": #stack default"
    addons:
      apt:
        packages:
        - libgmp-dev
  - env: BUILD=stack ARGS="--resolver lts-6"
    compiler: ": #stack 7.10.3"
    addons:
      apt:
        packages:
        - libgmp-dev
  - env: BUILD=stack ARGS="--resolver lts-8.3"
    compiler: ": #stack 8.0.2"
    addons:
      apt:
        packages:
        - libgmp-dev
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    addons:
      apt:
        packages:
        - libgmp-dev
  - env: BUILD=stack ARGS=""
    compiler: ": #stack default osx"
    os: osx
  - env: BUILD=stack ARGS="--resolver lts-6"
    compiler: ": #stack 7.10.3 osx"
    os: osx
  - env: BUILD=stack ARGS="--resolver lts-8.3"
    compiler: ": #stack 8.0.2 osx"
    os: osx
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ": #stack nightly osx"
    os: osx
  allow_failures:
  - env: BUILD=cabal GHCVER=head  CABALVER=head HAPPYVER=1.19.5 ALEXVER=3.1.7
  - env: BUILD=stack ARGS="--resolver nightly"
before_install:
- unset CC
- CABALARGS=""
- if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
  # Use the more reliable S3 mirror of Hackage
  mkdir -p $HOME/.cabal
  echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
  echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config
  if [ "$CABALVER" != "1.16" ]
  then
    echo 'jobs: $ncpus' >> $HOME/.cabal/config
  fi
install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
  '?')]"
- if [ -f configure.ac ]; then autoreconf -i; fi
- |
  set -ex
  case "$BUILD" in
    stack)
      stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
      ;;
    cabal)
      cabal --version
      travis_retry cabal update
      # Get the list of packages from the stack.yaml file
      PACKAGES=$(stack --install-ghc query locals | grep '^ *path' | sed 's@^ *path:@@')
      cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS $PACKAGES
      ;;
  esac
  set +ex
script:
- |
  set -ex
  case "$BUILD" in
    stack)
      stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      ;;
    cabal)
      cabal install --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS $PACKAGES
      ORIGDIR=$(pwd)
      for dir in $PACKAGES
      do
        cd $dir
        cabal sdist
        PKGVER=$(cabal info . | awk '{print $2;exit}')
        SRC_TGZ=$PKGVER.tar.gz
        cd dist
        tar zxfv "$SRC_TGZ"
        cd "$PKGVER"
        cabal configure --enable-tests
        cabal build
        cd $ORIGDIR
      done
      ;;
  esac
  set +ex
env:
  matrix:
  - secure: lLm2tiB3sZTpi44YSHo6okqNmgQPs0/L6UuHdGfZno7fmIuYVGNumm3WHTYwUFADJ49IF5Fa8tvhouUAhceFQZCW5gBhv/AzeUHPgfOGmZMuumoo5lF53eNZwDcZEgEl1MmtFAx19IqXNqVcCdD0OtCLlSTtVVgTZ5hOnsb6faSzbRqYJ5vO/9RblL79nMDX6s5ng/DsHrxGqAPR9mBq1Nq4tSCesfYE/r9oRe+pU4RFGQZdrsu837GyMS9St/acTXfedlQYJLnW0wtc/7sBsum4ZS2mWzUNMqVkJ/znOMCutx4hcKsGWAr4P5ebwy8nesIAkljZlUMnV9AliR6c0+HXf6IBoZ7fhPmU+Q+RWgg1bnPJBDmlfgzm6uBT7rGYmNVS8D7Voehsl7+u88lQo6/IKjiWSxWI1jAH7evSyaygZxV1im+NHuLpdjjf6NcpQkd/K2+Vxi9CgD+HNsIPTD+um+MFjn8nyV+N+rEZynfUqNrYy3Kko+WKevMrXw4LFuWCl9FxFzi3OEbppvEKqsw/eHtIxyTSJYEqGqShk1CQ8cUh7ks4Mrhp5YJ+KfL0+FWq2ZBxKTk7KLx4gj/AVypHT9G+/GZRJm/lmK1XF20WfXguCs28S2V0O9xODMsN4zygwBlZ5pvrkoOu0IsRF5egLTpZkrj00bEK8U0mLMg=
  - secure: QI2ttxOmjRSZFuk4Ediz29bhVDhT7xfRuX9f+NbAELltHN7gwnvBsjD8st7CXxrzFytLAyqRBitXooZrWGHTVL5Mfy7memqUCPFMuCLDFwiXppNDPjh8zdAMY4kAhYpanWWbo6rW6VXlFgpxLocjloOwkmNLajc+GpTfFGRVwaF6BUOGOEnzMk5O18LOBBolP9HrdPUCmMP01DiiDwFsertFVNhuX2AOgm7U1LtGZVeosvUT2g8gt0Qw8/W9lL4uW6xTBVyG/C2bihc+SN+Ue++c2e3OvgnpymSF9TXbbhak45WVhjg//KCngf39zro+eTSiXaajiU87aaMf83NoGA0wJW/IuaJMo2i9C+WGTN6qSGyToUUHt/Eu0a2JSZ57/NNnJhZ567GFnkN8RLOqJfn7dlH2OdKHnMaS7PSYNtqOuZR8o7YAG3jaOzHOoSmjoc4Ko/H+jOSRz0GD6yKTlet7MQ1zF5T2of7+TAuMQ17zorEo8CMxbknCnAWQMWvNNXtEj+glAelvIDE/w8k6LWqTTkC7w96MR3hqpb1VxwLlr88ATjpM5iArdu+KCeF7+KHggLSr/FxA/mjGp7fWc0+aG27qVl9sFrwreum9zBsMDwWeAnnOFNid/9eHOkEop4EzUDso/ArWzWMi57tKqb9D8eIS3+KWpOqBVpR1krs=
  - secure: XQnqzSujR2puTietqN1c7xjoH/WSWCo2Q2YMH8leseeStRLTo9jG5Mpl3sQcvhtuQWfVdTUphkfJrR2NYj9Hjuaj4XyptCPMwT5A8dVDa6OBZSiPB+wQuhLv386eUQFRbANA4Ex8h1OhV1BLqun94gwvlT2KqYfOZavJ97rw6r1e+Sq+fDw0u45ybkl4mOiXSUCgwS4aslxzM1oJ/mTnleFJ+auJdIhJM9iK2govdhQ1BKiFJmwS8dNubEvkaMI+XB/mLkIsXMvIq4ggMUd2E3K82xeiza5chQQSGM+4yud4KJocOwgPz5qTWHm1UBFpk9zlcjv0u0LfeRG8fVc77PMYbc3U3g4S4gyZMmUuxqgJnl7vQItkxXU40rWKr/t/RzE/KVMeX5mSjY5Z7Pltz5Z2Gcre8ArDTXuecCn+msdVHLtUG93HDIGvbDJp2sntsL8IzGeLHFqMQZPFFvAcSTlYbP5R+vduRSzgLvhxsNqrXXxqab5C/LuYYzNTNtVA3/V0c5EGKQC4gd6JHqAwcwyoFJSM2dCSt/QhfKqQIpwqUXpJGxQKHg5zYWqXL/suOYSe07IhY6qrvBp4Dpk8DxKycMQvaAgqSi7UXzlPnI3twwYfQhBMqHgZ0lshDHpnDU6jf05Sb4vME2O4WvBKkCxA5G2AX2WBg3YgwaI7JIo=
